### ISSUE TITLE
Información a publicar:

### ISSUE THREAD

**Issue by irafuls** [grafuls/fiscalia#2]
La aplicación debería reenviar de manera anónima a la pagina web información a cerca la evolución de la mesa según el número de la misma y una vez finalizado el proceso eleccionario debería sumar los certificados que se vayan cargando de las distintas mesas. Esto último debería ser sin ningún dato de trazabilidad y permitiendo solo una carga por mesa.

**Comment by sebacodoni** [comment]
okjñlk
